# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    bj.form_authenticator:
        class: BJ\UserBundle\Security\FormAuthenticator
        arguments: ["@security.password_encoder", "@router"]
        autowire: true